### ISSUE TITLE
10.1 POOL DE CONEXIONES CON PYTHON Y POSTGRESQL: Parte 1 (video 1)

### ISSUE THREAD

**Issue by GabJaJ** [CodeSystem2022/Perricornios-Tercer-Semestre#479]
**No hay código en este video, la persona asignada debe mostrar la imagen que subió el profe.**

**Comment by Noe3467** [comment]
También hice copia de Leccion07 para que se pueda trabajar sobre el archivo conexion.py (que es sobre el que traba el profe esta semana).Si todo está bien, cerrar issue.

**Comment by GabJaJ** [comment]
Tarea realizada con éxito, prosigo a cerrar.
